"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['YouTrackerLauncher.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': "images/youtrack.icns",
    'argv_emulation': True,
    'packages': ['rumps'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
